### ISSUE TITLE
Is this death? :(

### ISSUE THREAD

**Issue by tonibm19** [BizarreCake/hCraft#16]
So, will this project ever be updated to 1.8?

I really wanted to use this for a public creative server.

**Comment by BizarreCake** [comment]
A completely re-written hCraft 2 will be released some time soon. :)
Will be available for Windows too.

**Comment by tonibm19** [comment]
That sounds awesome, hopefully is sooner than later.

Thanks!

And, if you need testers, here I'm

**Comment by tonibm19** [comment]
That sounds awesome, hopefully is sooner than later.

Thanks!

And, if you need testers, here I'm
